spring.application.name=Airbnb_app


spring.datasource.url=jdbc:mysql://localhost:3306/airbnb
spring.datasource.username=root
spring.datasource.password=Anant@1234

#Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#database created once and it self get updated
spring.jpa.hibernate.ddl-auto=update
# sql commmand in console
spring.jpa.show-sql= true

server.port=8083 

#and also

server.servlet.context-path=/api/v1