spring.application.name=Airbnb_app


spring.datasource.url=jdbc:mysql://localhost:3306/airbnb_2
spring.datasource.username=root
spring.datasource.password=Anant@1234

#Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#database created once and it self get updated
spring.jpa.hibernate.ddl-auto=update
# sql commmand in console
spring.jpa.show-sql= true

server.port=8083 

#and also

server.servlet.context-path=/api/v1


jwt.secretKey=234e5ye4jk3nin32i4n32i4ned239rd92332nd9


# Razorpay


razorpay.key.id=rzp_test_Se5HV984ETdouz
razorpay.key.secret=rIsNlzPKUIqM5e0iw7QfHthr
razorpay.currency=INR
razorpay.business.name=Air Stay


